version: '3.8'

services:
  db:
    image: postgres:15
    container_name: finora_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: finora
    ports:
      - '5432:5432'
    volumes:
      - finora_db_data:/var/lib/postgresql/data

volumes:
  finora_db_data:
