export const ALLOWED_CATEGORY_ICONS = [
  'tag',
  'home',
  'wallet',
  'credit-card',
  'banknote',
  'piggy-bank',
  'shopping-cart',
  'shopping-bag',
  'store',
  'car',
  'bus',
  'plane',
  'bike',
  'utensils',
  'coffee',
  'apple',
  'pill',
  'heart-pulse',
  'dumbbell',
  'book-open',
  'briefcase',
  'laptop',
  'smartphone',
  'tv',
  'gamepad-2',
  'shirt',
  'gift',
  'wrench',
  'zap',
  'flower-2',
] as const;

export type AllowedCategoryIconSlug = (typeof ALLOWED_CATEGORY_ICONS)[number];
